### ISSUE TITLE
Add different levels of gold standard

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/posteriordb#107]
Micheal B suggested that we should have different levels of gold standards:
1. Pure analytical independent draws (gold)
2. Dynamic HMC draws that has been checked with SBC (silver)
3. Dynamic HMC checked (bronze)

This should be added as a slot in the gold standard info object.

**Comment by MansMeg** [comment]
So we add to the reference posterior if SBC has been checked or not. Then it can be computed automatically.

**Comment by eerolinna** [comment]
Do we still want the different levels (gold, silver, bronze etc)?

**Comment by MansMeg** [comment]
This will be fixed by adding SBC slot. Then we get this. It is just not called gold silver and bronze.

**Comment by eerolinna** [comment]
Great!

**Comment by MansMeg** [comment]
Done.
