### ISSUE TITLE
Change name of gold standard to reference, reference_draws, reference_info

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/posteriordb#113]
Also add reference_expectations for mean, variances and covariance

**Comment by eerolinna** [comment]
Should we rename `references` in
```json
  "references": [
    "rubin1981estimation",
    "gelman2013bayesian"
  ],
```
to `citations` (or something else) to avoid confusion?

**Comment by MansMeg** [comment]
Thats a very good idea!

**Comment by MansMeg** [comment]
I now tried this out, but citation does actually not make sense. We are essentially listing references for the data rather than citations for the data and that is a semantic difference. So I suggest we call it references and reference_posterior to make the distinction clear.

**Comment by eerolinna** [comment]
Hmm, that's a good point about `references` being better than `citations`. I still think it can be confusing to have `references` and `reference_posterior`. Could we rename `reference_posterior` to something else? Or perhaps rename `references` to something like `publications` or `publication_references`?

**Comment by MansMeg** [comment]
Alright. I and Aki discussed this briefly. I agree that it may be slightly confusing, but we could not come up with a better solution so Ill stick with `reference_posterior` and `references` for now.

**Comment by MansMeg** [comment]
Now fixed.
