### ISSUE TITLE
Add tests and gold standard systems information

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/posteriordb#116]
Diagnostics:
- ESS / iteration > 0.0001
- And the E-FMI threshold should be only 0.2.

In addition to the checks, also add slots in the gold standard that all these things have been checked for explicit in the gold standard.

Additional gold standard information:
R/Python version, the makevars file, the systemInfo()
(and equivalent for Python)

**Comment by eerolinna** [comment]
Which things exactly does the equivalent for python need to include?

**Comment by MansMeg** [comment]
So if we use python to compute a Gold standard we need to know the Python version, versions of additional libraries, and makevars? I guess there is a way to identify the ”state” that was run?

**Comment by eerolinna** [comment]
I don't think python has anything that is equivalent to R makevars. However I'm not fully sure if I understand what makevars are. Is it that makevars specifies the "environment variables" for building R packages?

Would we need versions of only the libraries that were actually used in the code that computes the gold standard or would it suffice to just include versions of all installed libraries?

What state are you referring to in the last sentence? Do you mean the things you mentioned in the previous sentence or something else?

**Comment by MansMeg** [comment]
I think the makevar file defines how the C++ compiler is used. Im not sure but I think it is used when compiling the Stan C++ code.

**Comment by MansMeg** [comment]
Yes, makevar is the compiler flags.

**Comment by MansMeg** [comment]
Now fixed.
