### ISSUE TITLE
Update documentation on how ess is handled

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/posteriordb#122]
We now check that the ESS is roughly within 4 SD from a NULL distribution (that is roughly sqrt(7 * S) where S is the total number of draws. This is a rough check for the ESS values, but far from perfect.

In the long run, we want to check this with a hierarchical model instead.

**Comment by avehtari** [comment]
Be more specific. ESS for which quantity?

**Comment by MansMeg** [comment]
Sure. ESS_bulk and ESS_tail for all parameters.

**Comment by MansMeg** [comment]
Now done.
