### ISSUE TITLE
Create constructors for all objects

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/posteriordb#123]
Model code, info, data, data info, rpd, rp info, rpe, posterior

Check stan code syntx automatically with the constructors

**Comment by eerolinna** [comment]
> Check stan code syntx automatically with the constructors

What does this mean?

**Comment by MansMeg** [comment]
We can use the stanc function in rstan to automatically check the stan code for syntax errors before they are constructed as stan code objects in R. This is mainly used to add new stan code to the db.

**Comment by eerolinna** [comment]
Sounds good, thanks for the clarification!

**Comment by MansMeg** [comment]
Now fixed.
