### ISSUE TITLE
Add contributor and date the model was added

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/posteriordb#15]
In data and model info, it would be good to have field for contributor and date added, maybe version for model
Contributor and date would help to increase trust that models are verified and track the contributor. We want the models to follow good practices and that means that when the prior recommendations or language changes we need sometimes to update models.

**Comment by eerolinna** [comment]
Great idea! What would be the identifier for a contributor?

**Comment by MansMeg** [comment]
I don't know. I guess just name.

**Comment by MansMeg** [comment]
Fixed
