### ISSUE TITLE
Python tests failing

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/posteriordb#154]
I have now rearranged in the database and fixed stuff that needed to be fixed. This mean that the structure has changed slightly and hence all the python tests are failing in the development branch.

These tests are now commented out since @jarnefeltoliver is adding posteriors to the database. 

It would be great if @jarnefeltoliver or @eerolinna could fix these issues in the Python library. Maybe @eerolinna could give a pointer to help @jarnefeltoliver?

**Comment by eerolinna** [comment]
Sure. Here's a guide on how to run the python tests: https://github.com/MansMeg/posteriordb/blob/master/doc/CONTRIBUTING.md#python-tests

This method of running the tests still works even though they are commented out from CI.

Try to get the tests to run. If you run into difficulties feel free to ask for help. Also if there's any difficulties we should improve the guide for next time.

The guide doesn't currently say this but you should run `tox` from the command line and do it from the `python` directory of this project.

You can make `tox` run the tests with just python 3.7 (or python3.6 if you have it installed but not 3.7), this should be sufficient for this situation. To do so, run `tox -e py37` (or py36 if you want to use 3.6).

Once you get the tests to run you'll see what they are failing on and might get an idea on how to fix them. I can help with that too if needed.

**Comment by eerolinna** [comment]
I think for future cases it would be good for Måns too to setup the python local tests. It should take just a few minutes. @MansMeg can you try it? The instructions are in the previous post.

**Comment by jarnefeltoliver** [comment]
Fixed this in #155 and modified also python README.md.

**Comment by MansMeg** [comment]
So you mean the two failing posteriors right? This is the issue for python failing tests?

**Comment by eerolinna** [comment]
Yes that was the issue. Did you look at the error message of the test?

**Comment by jarnefeltoliver** [comment]
Yes. It seems that now running tox everything passes.

**Comment by MansMeg** [comment]
There is still linting tests that is failing. I will try to fix it later today. Although I want to keep the issue up until all tests pass.

**Comment by eerolinna** [comment]
Ah yea, good point. Looks like they are fixed in https://github.com/jarnefeltoliver/posteriordb/commits/development just not PR'd yet

**Comment by eerolinna** [comment]
You can manually merge that branch already though, or wait for PR

**Comment by MansMeg** [comment]
Yes now done! Now I will merge with master. Great work!
