### ISSUE TITLE
Why copy code and data to R temp directory?

### ISSUE THREAD

**Issue by eerolinna** [MansMeg/posteriordb#16]
I'm not too familiar with R temp directory, what is the use case for copying model and data files to it? Is it needed?

I'm asking because python doesn't really have an equivalent concept and it would be great to keep the python and R versions as close to each other as possible.

**Comment by MansMeg** [comment]
Yes. I think this is a small difference. The R temp dir is removed when the R session is closed. So it is good to compile models in since it means that you will not break anything (like previous compiled models) and restarting your R session will fix everything.

**Comment by MansMeg** [comment]
Change the argument for data_path temp directory to cache_directory.

**Comment by eerolinna** [comment]
With the python package `dataset` unzips the data file on the fly (so doesn't copy it anywhere) while `dataset_file_path` makes a temporary file that contains the unzipped JSON.

 `model_code_file_path` on the other hand just returns the file path in the posterior database, not a file path to a temp file.

I guess these differences between R and python are fine. If so we can close this issue.

**Comment by eerolinna** [comment]
Closing this now
