### ISSUE TITLE
Setup Github Actions?

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/posteriordb#162]
We need to check that all path structures etc works with Windows.

**Comment by ahartikainen** [comment]
Have you considered Github Actions (It works with Linux, macOS and Windows). I can help with this if needed.

**Comment by MansMeg** [comment]
Nope. It sound very good! If you have any thought that would be great!

**Comment by MansMeg** [comment]
I have now implemented Appveyor, but moving to GitHub Actions might be better in the long run?
