### ISSUE TITLE
Renaming data column names in posterior files

### ISSUE THREAD

**Issue by eerolinna** [MansMeg/posteriordb#17]
If we have this model `linreg`
```stan
data {
  int<lower=0> N;
  vector[N] x;
  vector[N] y;
}
parameters {
  real alpha;
  real beta;
  real<lower=0> sigma;
}
model {
  y ~ normal(alpha + beta * x, sigma);
}
```

and dataset `sales` that is like
```json
{
  "advertising_spend": ["..."],
  "sales": ["..."]
}
```

it would be great if in the posterior file we could have something like

```json
{
  "model": "linreg",
  "data": "sales",
  "rename_data": {
    "advertising_spend": "x",
    "sales": "y"
  },
  "...": "..."
}
```
so that we could form a posterior of `linreg` and `sales`

**Comment by MansMeg** [comment]
Yes. But it increases the complexity so I think we skip it for now and maybe it is a natural extension later on.

**Comment by eerolinna** [comment]
I had an idea for how to make this more general. I don't think this is high priority but I wanted to write this down in case it might be useful at some point.

One way to achive this would be to have slots `data_transformation` and `data_transformation_arguments`.

So we might have
```json
{
  "model": "linreg",
  "data": "sales",
  "data_transformation": "rename",
  "data_transformation_arguments": {
    "advertising_spend": "x",
    "sales": "y"
  }
}
```

Then essentially the python and R packages would map "rename" to some function and call  `some_function(data, data_transformation_arguments)`

Essentially we would have a finite set of allowed `data_transformation` values and each of these would be mapped to some function in the `posteriordb` library.

Again, I don't think this is necessary at the moment but something to keep in mind.

**Comment by MansMeg** [comment]
Currently, this is solved in the design choices where we state that the data is static. So I close this one for now.
