### ISSUE TITLE
Reference vs gold standard / reference vs citation

### ISSUE THREAD

**Issue by mike-lawrence** [MansMeg/posteriordb#171]
The current version of `CONTRIBUTING.md` refers to "Gold standard posteriors", but it looks like that nomenclature was later changed to "Reference" posteriors as the link to the gold standard definition doc is broken and I now see a reference definition doc. Quick fix would be to update the contributing guide to use reference and not gold standard, but one nitpicky downside is that the contributing guide also talks about adding a new "reference", presumably meaning bibliographic information, which may cause confusion. Might I suggest that for this latter kind of addition the term "citation" is used instead?

**Comment by MansMeg** [comment]
Thank you, Mike! Yes, the COVID thing accidentally made me drop this in the middle. This should definitely be fixed. Thanks for noticing as well as for the issue. I will put this on the version 0.2 milestone and fix this asap.

**Comment by MansMeg** [comment]
The whole contributing document has now been rewritten. Thanks for noticing this!
