### ISSUE TITLE
Add license requirements for contributions

### ISSUE THREAD

**Issue by avehtari** [MansMeg/posteriordb#186]
Add to contributions doc information what licences we accept for Stan code to be included in posteriordb

**Comment by MansMeg** [comment]
Ok. What licences do we accept? I guess that as long as they are open? Or should we focus on MIT?

**Comment by avehtari** [comment]
It's better to be flexible, but the license should be permissive (free to distribute and modify, no commercial restrictions etc). I don't think we need to have explicit list, but maybe say something like "To get Stan code included in posteriordb git repo, the license for the code needs to be permissive such as BSD3, MIT, GPL, etc"

It seems posteriordb itself is currently missing LICENSE file. We could use the same as for posterior https://github.com/stan-dev/posterior/blob/master/LICENSE.md

**Comment by MansMeg** [comment]
I think it will be hard to have separate licenses for different code in the same project. I suggest that we use the same as posterior and then say that of they supply code it will have that licence? That should be more simple, or?

**Comment by avehtari** [comment]
We can encourage BSD3, but it's not hard to have different licenses. Each file can have their own license, and we just don't accept licenses that are too restrictive to be compatible.

**Comment by avehtari** [comment]
I would not like to stop adding a model that has compatible license but that just is different than the license for the package code.

**Comment by MansMeg** [comment]
Alright. This seems reasonable. We will just add an additional slot in the model code info and data info json objects.

**Comment by MansMeg** [comment]
Now done by adding this to the CONTRIBUTING.md file
