### ISSUE TITLE
Typo in function 'reference_posterior_info'  instruction in Readme

### ISSUE THREAD

**Issue by LuZhangstat** [MansMeg/posteriordb#187]
Hi, 

   I ran the example code in the Readme file and got the following error 

`> rp_info <- reference_posterior_info(po)
Error in read_reference_posterior_info(x = x$reference_posterior_name,  : 
  argument "type" is missing, with no default`

Then I checked the help document and made the function work through 
`rp_info <- reference_posterior_info(po, type = "draws")`

 Would you like to double-check it and fix the typo? Many thanks.

Best,

**Comment by MansMeg** [comment]
Hi! Im just back from vacation. Thanks! Ill look into this asap.

**Comment by MansMeg** [comment]
This is now fixed. Thanks!
