### ISSUE TITLE
rewrite purpose of the PDB

### ISSUE THREAD

**Issue by bob-carpenter** [MansMeg/posteriordb#207]
I'd suggest the following replacement for the start of the top-level `README.md`.   My motivation in rewriting is to

* elminate redundancy,
* write in more direct sentences directed at the user,
* mention the name posteriordb in the title and in the text,
* separately describe what it is and what it can be used for,
* de-emphasize Stan (you may want to put that back in, maybe as an example of probabilistic programming framework for which `posteriordb` provides models),
* distill uses down to just testing of various forms and education, and
* add that it's intended to test approximate algorithms.

After the rewrite, I don't think `doc/use_cases.md` adds anything.  If you do decide to elaborate that more, I'd suggest linking it from the what-it-can-be-used-for section.

------

# `posteriordb`: a database of Bayesian posterior inference

## What is `posteriordb`?

`posteriordb` is a set of Bayesian statistical models and data sets, reference implementations in probabilistic programming languages, and reference posterior inferences in the form of posterior samples.   

## Why use `posteriordb`?

`posteriordb` is designed to test inference algorithms across a wide range of models and data sets.  Applications include testing for accuracy, testing for speed, and testing for scalability.  Algorithms being tested may be approximate like variational inference or asymptotically exact like Markov chain Monte Carlo.  `posteriordb` can be used to test new algorithms being developed or deployed as part of continuous integration for ongoing regression testing of algorithms in probabilistic programming frameworks.

`posteriordb` also makes it easy for students and instructors to access a range of pedagogical and real-world examples with precise model definitions, well-curated data sets, and reference posteriors.  

`posteriordb` is framework agnostic and easily accessible from R and Python.  

-----

**Comment by MansMeg** [comment]
Yes! This is a good idea. I will fix this. I still think we want to keep the use cases md file for now since there is quite a lot of discussion what is the use cases of posteriordb. Thanks Bob!

**Comment by MansMeg** [comment]
Now fixed.

**Comment by avehtari** [comment]
Thanks Bob!
