### ISSUE TITLE
Add LICENSE file for python

### ISSUE THREAD

**Issue by ahartikainen** [MansMeg/posteriordb#216]
We should have a LICENSE file for Python which will be added to wheel + PyPI. (`MANIFEST.in` file)

See example here https://github.com/arviz-devs/arviz/blob/master/MANIFEST.in

We could use https://github.com/licenses/lice

or

https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by MansMeg** [comment]
Sounds reasonable. Do you need anything from me for this?

**Comment by MansMeg** [comment]
This is done now, right?

**Comment by ahartikainen** [comment]
Yes
