### ISSUE TITLE
Rename to posterior_db?

### ISSUE THREAD

**Issue by eerolinna** [MansMeg/posteriordb#22]
`posterior_db` feels like a more clear name for this repo to me than `posteriordb`

**Comment by eerolinna** [comment]
What do you think?

**Comment by eerolinna** [comment]
Is it so that R doesn't allow packages with underscores in the name? https://stackoverflow.com/questions/55179098/how-do-i-create-a-package-name-with-underscore?noredirect=1 seems to suggest so.

In python I would say `posterior_db` is more idiomatic than `posteriordb`, but maybe it would be better to be consistent between python and R. In that case it's of course best to call the repo `posteriordb` too.

**Comment by MansMeg** [comment]
Yes. Indeed!

**Comment by eerolinna** [comment]
I'll need to rename the python package, lets keep this issue open till that is done.

**Comment by MansMeg** [comment]
Yes. Sounds good!
