### ISSUE TITLE
Add installing package and pointing the database to github

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/posteriordb#41]
Now we need to clone the db to use it. It would be better to just install an R package and then as default point the database to the github repository. Then users do not need to download as much (but will only be able to use the latest models.

**Comment by eerolinna** [comment]
I guess this should be implemented by downloading models, datasets etc to a cache or data directory. Probably only the models the user uses should be downloaded.

I found a python package for accessing platform specific data/cache/config directories, https://github.com/ActiveState/appdirs

For example for the user `trentm` the cache dir on MacOS would be `/Users/trentm/Library/Caches/posteriordb`, on Windows `C:\Users\trentm\AppData\Local\author_name\posteriordb\\Cache` (`author_name` could also be `posteriordb`) and on Linux `/home/trentm/.cache/posteriordb`

The main technical challenge is probably determining when a downloaded file is stale and needs to be downloaded again. One approach would be having a file in this repo that contains hashes of each file in the posterior database. Then with the hash we could be determine if a file needs to be re-downloaded. There are other approaches too, such as just redownloading everything once a new version of `posteriordb` is released.

**Comment by eerolinna** [comment]
Another possibility would be to include the whole PDB in the R and python packages (or as a separate `posteriordbdata` package). With this approach we wouldn't need to worry about platform-specific directories, but using this would mean that that the package needs to be updated to access new models etc and also that the whole database is always downloaded even if the user wants to use only a few posteriors

**Comment by MansMeg** [comment]
Yes. No I think we do not want to include the data in the packages. Partly because in the long run we want to have an online db.

**Comment by MansMeg** [comment]
Downloading it to cashe is the idea. I think the easiest thing is to have a temporary cashe (ie R temp folder) and the pasobility to point to a new cashe that is mor stable. The purpose of this issue is to remove the need to clone the repo to access the db. 

I guess stale files can be identified by the git sha. If we limit to point to DB on github/using git. I think such a limitation i reasonable for now.

**Comment by eerolinna** [comment]
I feel a persistent cache is the way to go, having to download the models and datasets again just because R session was closed doesn't feel good to me.

So with the git sha approach we redownload everything when the PDB gets new commits? I agree that for the first version this is good enough, it can be improved later.

**Comment by MansMeg** [comment]
Yes, it should be up to the user. I think as default in R the temp dir is good. But more advanced users may want a persistant cache. Think students playing with models in R vs people doing large-scale experiments.

So if I remember github it contains sha for the commit of the individual file. So it is only the sha of the commit where the file was changed.

**Comment by eerolinna** [comment]
A few questions:

1. If the user calls `pos <- posterior_names(my_pdb)` is it OK that all the posterior info files in  `posteriors/` get downloaded? And same with `model_names` and `dataset_names`

2. Is it best to not yet download the dataset file and model code when the user calls `po <- posterior("8_schools-8_schools_centered", my_pdb)` and instead download them when the user calls `dataset(po)` or `stan_code(po)`? And the same applies for downloading the model info and dataset info files.

    The posterior info however would be downloaded at this point.

    A downside to this approach is that it can be hard to validate the the posterior has valid dataset and model code.

**Comment by MansMeg** [comment]
This has now been solved. It just needs to be updated in the vignette and documentation.

**Comment by eerolinna** [comment]
Good job!

**Comment by MansMeg** [comment]
To eeros comment above. I have now added a cache_path to the pdb object so it is can be stored wherever. If we want we can point the local db path to be the cache, then nothing is cached.
