### ISSUE TITLE
Add metadata filter functions

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/posteriordb#43]
Add meta-data filter: 
can you filter after meta-data of the posterior? Both for posteriors, data and models.

**Comment by MansMeg** [comment]
Have you a status here @paul-buerkner ?

**Comment by paul-buerkner** [comment]
Oh, for some reasons, I overlooked I was assigned for it. Sorry, I didn't take any further look at this. 
Do you have a proposal for how to do it already? Otherwise, I will think about it a little bit more today.

**Comment by MansMeg** [comment]
Not really. I think this defines a little how we would access/filter in the databases so maybe have ashort discussion on it. I could also do the work, but the API need some thinking.

**Comment by paul-buerkner** [comment]
I agree. Let's think of this a little bit more and then have a discussion to make some decisions about this, maybe thursday or friday?

**Comment by MansMeg** [comment]
Thursday is great. Maybe before noon?

**Comment by paul-buerkner** [comment]
Sounds good.

**Comment by MansMeg** [comment]
Summary of discussion:
We implement the filter function based on the dplyr filter function, essentially using the same framework. The API will be:
```
pos <- pdb_filter_posterior(.pdb, ...)
ms <- pdb_filter_models(.pdb, ...)
ds <- pdb_filter_data(.pdb, ...)
```
Here ... is filtering syntax according to the dplyr filter function:
https://dplyr.tidyverse.org/reference/filter.html

This would mean that we would implement this as three steps:
1.  create a pdb_posteriors_df() function to create a posterior/model/data tibble for all elements in the posterior database. Here we expand all keyterms.
2. Use dplyr::filter() to select from the tibble.
3. Return posteriors as read posterior objects.

**Comment by paul-buerkner** [comment]
Lovely, I am very happy with this interface. One minor comment. You use `posterior` in singular and `models` in plural. Does your plan to have singular/plural aliases still apply or shall we settle for just one of them?

**Comment by MansMeg** [comment]
Good point. I think using both would be reasonable (using alias).

**Comment by eerolinna** [comment]
I'm not familiar with dplyr syntax, can you show me how these queries should be written?

1. Find all posteriors where the model was added by Måns.

   My attempt
   ```R
   ms <- pdb_filter_models(.pdb, added_by == "Måns Magnusson")
   posteriors <- ??
   ```

2. Find all posteriors where the model has keyword `bda3_example`.

3. Same as 2. but only find posteriors that have a gold standard.
