### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by eerolinna** [MansMeg/posteriordb#55]
I feel there might be some disconnect between how we use terms like `posterior`, `dataset` (or just `data`) and `model` and how users would use the terms.

Here's some possible descriptions the users and we might use (feel free to suggest improvements)

Users might describe `posterior` as a posterior distribution for model parameters while we (as in the PDB implementators) use `posterior` to mean a model, a dataset and a posterior distribution for them. We also give each posterior a name.

Users might describe `dataset` as a matrix of observations and attributes. We might describe it as information (like citation that introduced the dataset) along with the matrix. We also give each dataset a name.

Users might describe `model` as a statistical relationship between (some) attributes of the data (which could be specified with a programming language). We might describe it as information (like citation) along with the statistical relationship. We also give each model a name.

# Python examples
## Model
```python
from posteriordb import PosteriorDatabase
posterior_database = PosteriorDatabase("folder_of_pdb")
posterior_database.model("8_schools_centered")
```
The users might think this returns the model code for the 8 schools model, however getting the model code requires `posterior_database.model("8_schools").code("stan")`

## Dataset
```python
posterior_database.dataset("8_schools")
```
The users might think this returns the loaded JSON dataset. That instead requires `posterior_database.dataset("8_schools").data()`

## Posterior
```python
posterior_database.posterior("8_schools-8_schools_centered")
```
The users might think this returns the samples from the posterior distribution of model parameters, however to do that requires `posterior_database.posterior("8_schools-8_schools_centered").gold_standard().posterior_draws()` (this part is not implemented yet)

# R

The R library doesn't fully suffer from the same issues as `get_data(po)` returns the loaded JSON and `model_code(po, "stan")` returns the actual model code.

However this also means that `model` and `dataset` are not first-class entities in R. Let's say we want to search for all the hierarchical models and for each model print the references of that model. This will be more difficult if `model` is not a first-class entity.

# What to do?

I don't know if there's a good solution for this mismatch in how we use the terms compared to how users might use them. Ideally we would try to find a set of terms that would have the same meaning for us and the users and have the API use those terms. This might be hard.

What do you think? @paul-buerkner @MansMeg 
Also, if you can think of better definitions of these terms both from the users perspective and from our perspective (so the implementors perspective) those are welcome

**Comment by eerolinna** [comment]
I would appreciate some comments. Is it that you agree with these observations but have no concrete suggestions to improve the situation (I fall in this camp right now)? Or that you disagree with something here, or you feel like this is not an important issue, or something else?

**Comment by MansMeg** [comment]
I will read. I just have not had the time yet.

**Comment by MansMeg** [comment]
So. Now I have read this. I think the way we think of this is quite good. I agree with you that it may be slightly confusing to users, but the important thing is that we now are satisfied with this. I think showing good examples that users can read will simplify this and would be a good idea.

I now remove this issue from the Prototype, although not closing the issue.

**Comment by MansMeg** [comment]
I close this issue now. If we want we can improve this later on.
