### ISSUE TITLE
Better repository structure

### ISSUE THREAD

**Issue by MansMeg** [MansMeg/posteriordb#56]
I think we should clean up the repo before prototype release, especially since we now have both Python and R data. I have the following suggestions:
1. Remove contents/datasets-raw? I guess this is just legacy stuff left.
2. Change "content" to "pdb" and move posterior into "pdb"?

**Comment by eerolinna** [comment]
I don't have an opinion on 1. I don't think 2 is necessary but if you feel it would be good I won't be against it. 

If you choose to go for 2 I would appreciate if you tried making the necessary changes to the python package yourself (I will of course help if you get stuck). I think the only file that needs changes is https://github.com/MansMeg/posteriordb/blob/master/python/src/posteriordb/posterior_database.py

**Comment by MansMeg** [comment]
It start to become slightly crowded in the repo. Thats why.

**Comment by eerolinna** [comment]
Hmm, on a second thought I think the change of moving `posteriors` under `content` would be good.

I'm not sure if `content` needs to be renamed. We would have `content`, `rpackage` and `python`, I feel like `content` would be fine here as it says that the contents of `posteriordb` are here. Or perhaps it could be called `contents`.

If we were to rename it I would prefer something like `posterior_database` over `pdb`.

**Comment by MansMeg** [comment]
Alright! I use `posterior_database`!

**Comment by eerolinna** [comment]
Can you also have a go with updating the python library with these changes? I'll help if you get stuck. I think https://github.com/MansMeg/posteriordb/blob/master/python/src/posteriordb/posterior_database.py is the only file that needs to be modified. It would be good if I'm not the only person who knows the python codebase

**Comment by MansMeg** [comment]
Ill see what I can do but I do not want to put too much effort outside the R package right now.

**Comment by eerolinna** [comment]
I think spending 20 minutes on the python library should be enough, if it takes more than that let me know and I'll finish it.

**Comment by MansMeg** [comment]
This has now been done - except handling python.

**Comment by eerolinna** [comment]
Great! Are you going to try fixing the python library? (No need to spend over 20 mins)

**Comment by MansMeg** [comment]
Ill give it a try but probly later in the week.
